definitions:
  AdmitPatientRequest:
    description: Patient to be admitted
    properties:
      patient_age:
        type: integer
      patient_name:
        type: string
      ward_number:
        type: string
    type: object
  AdmitPatientResponse:
    properties:
      patient_id:
        type: string
    type: object
  DischargePatientRequest:
    properties:
      discharge_note:
        type: string
    type: object
  HTTPError:
    properties:
      code:
        type: integer
      error: {}
    type: object
  TransferPatientRequest:
    properties:
      new_ward_number:
        type: string
    type: object
info:
  contact: {}
  description: This is an Event-Sourced Clinic example.
  title: Event-Sourced Clinic Example API
  version: "1.0"
paths:
  /patients/{id}/discharge:
    post:
      consumes:
      - application/json
      description: discharges a patient.
      parameters:
      - description: Patient Id
        in: path
        name: id
        required: true
        type: string
      - description: Discharge request
        in: body
        name: DischargePatientRequest
        required: true
        schema:
          $ref: '#/definitions/DischargePatientRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Discharge a patient
      tags:
      - Patients
  /patients/{id}/transfer:
    post:
      consumes:
      - application/json
      description: transfers patient to a new ward.
      parameters:
      - description: Patient Id
        in: path
        name: id
        required: true
        type: string
      - description: Transfer request
        in: body
        name: TransferPatientRequest
        required: true
        schema:
          $ref: '#/definitions/TransferPatientRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Transfer a patient
      tags:
      - Patients
  /patients/admit:
    post:
      consumes:
      - application/json
      description: admits a new patient.
      parameters:
      - description: Patient to admit
        in: body
        name: AdmitPatientRequest
        required: true
        schema:
          $ref: '#/definitions/AdmitPatientRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Admitted patient
          schema:
            $ref: '#/definitions/AdmitPatientResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Admit a new patient
      tags:
      - Patients
swagger: "2.0"
